# Generated by Django 2.1.1 on 2018-12-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=20)),
            ],
            options={
                'db_table': 'v_video',
            },
        ),
    ]
