# Generated by Django 2.1.1 on 2018-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_sex', models.CharField(max_length=10)),
                ('student_age', models.CharField(max_length=10)),
            ],
        ),
    ]
